name: nixos
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-nixos.yml'
      #- '**.nix'
      - 'flake.*'
  pull_request:
    paths:
      - '.github/workflows/ci-nixos.yml'
      - '**.nix'
      - 'flake.*'
  #schedule:
    #- cron: '11 3 * * *'
  workflow_dispatch:

jobs:
  nixos:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        hostname: 
          - tower
          - x13
          - oca
          - lsrv
    steps:
    - run: |
        sudo rm -rf $AGENT_TOOLSDIRECTORY
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/lib/node_modules
        sudo rm -rf /usr/local/lib/heroku
        sudo rm -rf /var/lib/docker/overlay2
        sudo rm -rf /home/linuxbrew
        sudo rm -rf /home/runner/.rustup 
    - run: |
         DEBIAN_FRONTEND=noninteractive
         sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
      if: contains(matrix.hostname, 'oca')
    - name: Maximize build space
      uses: easimon/maximize-build-space@v10
      with:
        remove-android: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'
        #build-mount-path: /nix
        swap-size-mb: 1024
        root-reserve-mb: 50192
    - uses: actions/checkout@v4.2.2
    - uses: DeterminateSystems/nix-installer-action@v16
      with:
        extra-conf: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux arm-linux i686-linux
    - uses: DeterminateSystems/flake-checker-action@v9
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - uses: cachix/cachix-action@v15
      with:
        name: chr 
        extraPullNames: 'nix-community, chaotic-nyx, cosmic'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Apply Nix binary cache configuration
      run: |
        sudo tee -a /etc/nix/nix.conf > /dev/null <<EOF
        extra-substituters = https://cache.nixos.org https://nix-community.cachix.org https://nyx.chaotic.cx/ https://chaotic-nyx.cachix.org https://cache.garnix.io extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nyx.chaotic.cx-1:HfnXSw4pj95iI/n17rIDy40agHj12WfF+Gqk6SonIT8= chaotic-nyx.cachix.org-1:HfnXSw4pj95iI/n17rIDy40agHj12WfF+Gqk6SonIT8= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
        EOF
    - run: 'nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel --accept-flake-config'
      continue-on-error: true
