name: nixos
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-nixos.yml'
      #- '**.nix'
      - 'flake.*'
  pull_request:
    paths:
      - '.github/workflows/ci-nixos.yml'
      - '**.nix'
      - 'flake.*'
  #schedule:
    #- cron: '11 3 * * *'
  workflow_dispatch:

jobs:
  nixos:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        hostname: 
          - tower
          - x13
          - oca
    steps:
    - run: |
        sudo rm -rf $AGENT_TOOLSDIRECTORY
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/lib/node_modules
        sudo rm -rf /usr/local/lib/heroku
        sudo rm -rf /var/lib/docker/overlay2
        sudo rm -rf /home/linuxbrew
        sudo rm -rf /home/runner/.rustup 
    - run: |
         DEBIAN_FRONTEND=noninteractive
         sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
      if: contains(matrix.hostname, 'oca')
    - name: Maximize build space
      uses: easimon/maximize-build-space@v9
      with:
        remove-android: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'
        #build-mount-path: /nix
        swap-size-mb: 1024
        root-reserve-mb: 50192
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v14
      with:
        extra-conf: |
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux arm-linux i686-linux
    - uses: DeterminateSystems/flake-checker-action@v4
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - uses: cachix/cachix-action@v15
      with:
        name: chr 
        extraPullNames: 'nix-community'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: 'nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel'
