name: nixos
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-nixos.yml'
      #- '**.nix'
      - 'flake.*'
  pull_request:
    paths:
      - '.github/workflows/ci-nixos.yml'
      - '**.nix'
      - 'flake.*'
  #schedule:
    #- cron: '11 3 * * *'
  workflow_dispatch:

jobs:
  nixos:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        hostname: 
          - tower
          - x13
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v14
    - uses: DeterminateSystems/flake-checker-action@v4
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - uses: cachix/cachix-action@v15
      with:
        name: chr 
        extraPullNames: 'nix-community'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: 'nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel'
